apiVersion: v1
kind: Service
metadata: 
    name: loadbalancer-service
spec:
    selector:
        app: fiapapipod
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: LoadBalancer